coverage:
  status:
    project: # more options at https://docs.codecov.com/docs/commit-status
      default:
        target: auto # use the coverage from the base commit, fail if coverage is lower
        threshold: 0% # allow the coverage to drop by

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false # [true :: must have a base report to post]
  require_head: false # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]
