requirements_file: doc/manual/requirements.txt

python:
  version: 3
  setup_py_install: true
  use_system_site_packages: true

# For more fields that can be specified here, see:
# http://docs.readthedocs.io/en/latest/yaml-config.html
